name: Continuous Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      local-path:
        required: true
        type: string
      remote-path:
        required: true
        type: string
      docker-file-path:
        required: true
        type: string
      tag:
        required: true
        type: string
      artifact-path:
        required: true
        type: string
      deploy-script:
        required: true
        type: string

    secrets:
      HOST:
        required: true
      SSH_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true



jobs:
  docker:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}_docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.0
          buildkitd-flags: --debug
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ${{inputs.artifact-path}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{inputs.docker-file-path}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          push: true
          tags: ${{inputs.tag}}


  deploy-dev:
    needs: docker
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Files with Password
        run: |
          sshpass -p "${{secrets.SSH_PASSWORD}}" \
          rsync -avz --progress --rsh="ssh -o StrictHostKeyChecking=no" \
          ${{inputs.local-path}} \
          ${{secrets.SSH_USER}}@${{secrets.HOST}}:${{inputs.remote-path}}

      - name: Run Deployment Script with Password
        run: |
          sshpass -p "${{secrets.SSH_PASSWORD}}" \
          ssh -o StrictHostKeyChecking=no \
          ${{secrets.SSH_USER}}@${{secrets.HOST}} \
          "${{inputs.deploy-script}}"

      - name: install ssh keys
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: ${{inputs.deploy-script}}